environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"

platform:
- x86
- x64

# configuration: Release

os :
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g node-gyp
- npm install -g node-pre-gyp	# to allow use as command in a console.
- node-pre-gyp configure
- node-pre-gyp /m build
- npm install node-pre-gyp		# to allow use as module in a JS file.	

build: off

test_script:
- node demo.js

# matrix:
  # allow_failures:
  # - os: Visual Studio 2017

