os:
- linux
- osx

dist: trusty

language: node_js

node_js:
- "7"
- "6"
- "5"
- "4"

script:
# Both below commands are already done.
#- npm install node-pre-gyp
#- node-pre-gyp configure
- make -j 4
# Above command is faster as below one.
#- node-pre-gyp -j 4 build
- node demo.js
